### ISSUE TITLE
public.php, index.php

### ISSUE THREAD

**Issue by MktHunter** [thomasjacquin/allsky-portal#12]
line 23 in public.php and lines 38 & 39 in index.php are building the wrong file names due to underscore and possible $cam value.

**Comment by thomasjacquin** [comment]
What camera is selected in your `config.sh`?

**Comment by MktHunter** [comment]
Contents from a yesterday download. I did some edits but there is no entry for "CAMERA=", only CAMERA_SETTINGS


pi@allsky:~/allsky $ cat config.sh
#!/bin/bash
source /home/pi/allsky/scripts/ftp-settings.sh

# Set to true to upload current image to your website
UPLOAD_IMG=false

# Set to true to upload timelapse video to your website at the end of each night
UPLOAD_VIDEO=false

# Set to true to send data to your server at the end of each night
POST_END_OF_NIGHT_DATA=false

# Set to true to generate a timelapse at the end of the night
TIMELAPSE=true

# Timelapse frame rate (number of frames per second)
FPS=25

# Set to true to generate a keogram at the end of the night (image summary of the night)
KEOGRAM=true

# Set to true to upload the keogram after it has been generated
UPLOAD_KEOGRAM=false

# Set to true to generate a startrails image of the night. Will skip brighter images to avoid over-exposure
STARTRAILS=true

# Images with a brightness higher than the threshold will be skipped for startrails image generation
BRIGHTNESS_THRESHOLD=0.1

# Set to true to upload the startrails after it has been generated
UPLOAD_STARTRAILS=false

# Set to true to enable automatic deletion of archived data (images + videos)
AUTO_DELETE=true

# Set this value to the number of archived nights you want to keep. Needs AUTO_DELETE=true to work
NIGHTS_TO_KEEP=10

# Path to the dark frame for hot pixels subtraction. Can be jpg or png.
DARK_FRAME="dark.jpg"

# Set to 0 to disable Daytime Capture
DAYTIME="1"

# Path to the camera settings (exposure, gain, delay, overlay, etc)
CAMERA_SETTINGS="/etc/raspap/settings.json"
pi@allsky:~/allsky $

**Comment by thomasjacquin** [comment]
Then you probably don't have the most recent code.

Here's the new code: https://github.com/thomasjacquin/allsky/blob/master/config.sh.repo

**Comment by MktHunter** [comment]
From gui/install_RPiHQ.sh
git clone https://github.com/thomasjacquin/allsky-portal.git /var/www/html


You might need to edit this:
From https://github.com/thomasjacquin/allsky where I got the link and installed yesterday
----------------------------
Now fetch the code from this GitHub page. Open the terminal and type the following:

git clone --recursive https://github.com/thomasjacquin/allsky.git
---------------------------

**Comment by MktHunter** [comment]
Had to delete my last comment
I downloaded base from a saved doc using
git clone https://github.com/RobboRob/allsky.git
