### ISSUE TITLE
LiveView not working

### ISSUE THREAD

**Issue by castropic** [thomasjacquin/allsky-portal#16]
hello, I just installed both packages allsky and allsky-portal for the Raspberry Pi HQ Camera. Unfortunately I don't get a picture in Live View. In the path /var/www/html/current there is a live-image.jpg

**Comment by EricClaeys** [comment]
Please try with the new version of the admin GUI and new version of "allsky" that were posted a couple weeks ago,  and let me know if you are still having problems. 
Eric

**Comment by EricClaeys** [comment]
castropic,
Have you tried with version 0.7 ?  It it works, please close this issue.
Thanks much - Eric

**Comment by EricClaeys** [comment]
Closing issue - no reply from user in over a month.
