### ISSUE TITLE
Add Custom Task Start

### ISSUE THREAD

**Issue by widobsono** [thomasjacquin/allsky-portal#18]
Hi guys, I love this system. Thanks for the amazing software.

I am curious how to add another script manager (to start or stop), I want to combine this with pySQM for Unihedron Sky Quality Meter (https://github.com/mireianievas/PySQM) so I can monitor and add some more features. 

I tried modifying some stuff inside the index.php, but when I reload the page, it won't change the web GUI. I restarted lighttpd assuming all the `.php` scripts would be reloaded, but nothing changed.

**Comment by EricClaeys** [comment]
Widobsono, you may need to force your browser to refresh the page - you can clear the cache of press F12 when in the page, and on the "Network" tab there's an option for disable cache.  Click it, then refresh the page.
Eric

**Comment by EricClaeys** [comment]
widobsono, did it work?

**Comment by widobsono** [comment]
Yes, turns out after another clean Install I managed to solve the problem. Thank you :D
