### ISSUE TITLE
Nice feature: "Virtual Sky" in Live view  [possible new feature]

### ISSUE THREAD

**Issue by AndreasLMeg** [thomasjacquin/allsky-portal#19]
For my family members I have now shown a picture of the current star configurations in the live view (embedded from https://virtualsky.lco.global/embed/custom.html)

Maybe this is also interesting for others

No automation (position, orientation)

(Sorry - I'm a newbie to HTML!)
 
[liveview.zip](https://github.com/thomasjacquin/allsky-portal/files/6720011/liveview.zip)

**Comment by AndreasLMeg** [comment]
![grafik](https://user-images.githubusercontent.com/85451655/123511950-d905df80-d684-11eb-8e47-da1c6ac63fc4.png)

**Comment by AndreasLMeg** [comment]
![grafik](https://user-images.githubusercontent.com/85451655/123528910-c7a3ee00-d6eb-11eb-8460-75ab5aa7e05e.png)

**Comment by EricClaeys** [comment]
@AndreasLMeg I'll leave this issue open for a while so we can discuss possibly adding it.  If we do, it would likely be to the website created by the allsky-website package, not the admin GUI which is normally only viewable by the administrator of the Pi.

**Comment by linuxkidd** [comment]
@AndreasLMeg -- Have you seen the virtual sky overlay in the allsky-website package?  It takes some fiddling to get it to align properly, and it drifts a little out of alignment and then back into alignment ( depending on the time of year ).. but overall it's pretty cool.  You can see it in action on my public page ( lots of clouds, so ... tough to tell it aligns to anything right this second )
https://allsky.linuxkidd.com

It's the Cassiopeia icon at the top of the left menu bar to toggle it on or off.

**Comment by EricClaeys** [comment]
@AndreasLMeg, do you give family and friends access to the WebUI?  Usually the Allsky website's URL is given to other people, and it can display the constellation overlay.

@linuxkidd, FYI

**Comment by EricClaeys** [comment]
@AndreasLMeg. ?

**Comment by EricClaeys** [comment]
@AndreasLMeg   Glad the current version satisfies your needs.
I've realized for years that I enjoy "improving" things, including software - mine and other people's.
Thanks for closing the Issue.
