### ISSUE TITLE
Add the camera to video surveillance software

### ISSUE THREAD

**Issue by Amenophis54** [thomasjacquin/allsky-portal#30]
Hello,

I would like to add the allsky camera in the iSpy software but I cannot find the address with the video / images stream.
Indeed, during my astrophotography sessions, I run iSpy to connect to my hardware surveillance camera.

I would therefore like to take the opportunity to see the sky as well.

Thank you.

Thomas.

**Comment by EricClaeys** [comment]
Thomas, for the ZWO cameras the AllSky software uses the ZWO SDK.  For RPiHQ cameras we use the raspistill command to handle all picture-taking.  You can look at capture.cpp (ZWO) or capture_RPiHQ.cpp to see how we do it.
What address are you referring to?

**Comment by linuxkidd** [comment]
I think what @Amenophis54 is looking for is akin to an RTSP stream like security cameras provide.  Unfortunately, that's just not how the allsky setup works.  The camera itself performs the exposure and provides a final long-exposure image via the API to the software.  There isn't actually a 'stream' link that could be provided.

The only option, if supported by iSpy, would be to poll for an updated image every X seconds ( X to match the new image interval of your allsky config ).  I don't know if that's possible, but seems a reasonable thing for iSpy and similar software to support.

**Comment by EricClaeys** [comment]
@Amenophis54   Thomas, I'm closing this Issue.  @linuxkidd gave a suggestion, and we're very unlikely to implement this enhancement - the expected audience is too small.
