### ISSUE TITLE
With RPiHQ camera set, camera page still shows ZWO settings?

### ISSUE THREAD

**Issue by ssagerian** [thomasjacquin/allsky-portal#42]
When I set the camera type to RPiHQ and restart the GUI, the camera settings page still shows settings for ZWO

**Comment by ssagerian** [comment]
![allsky_editor_wRPiHQ](https://user-images.githubusercontent.com/3128943/136664807-1ceade78-1946-4a06-9dd6-906ed4e1ff18.png)
![allsky_camera_setting_ZWO](https://user-images.githubusercontent.com/3128943/136664823-36a35b6e-fc0f-4975-91b2-303f49e6dfa3.png)

**Comment by EricClaeys** [comment]
@ssagerian Steve, would you please scroll down in the Camera Settings page to the bottom, then click on the "Show advanced options" and let me know if there's an option for `Version 0.8 Exposure`?  If there is, then the page is showing the wrong file.  If there isn't, then it's just the title that's wrong.
Thanks, and Hi.  This is Eric Claeys

**Comment by ssagerian** [comment]
Hi Eric, How many Eric Claeys are there? I see a Version 0.8 in the advanced setting.
Here is a screen shot of the advance settings..
Steve S

![RPiHQ_notsettings](https://user-images.githubusercontent.com/3128943/136693114-72ed83d5-b8d9-4006-a785-ee1da7abee15.PNG)
s.

**Comment by EricClaeys** [comment]
@ssagerian I submitted what I believe is a fix for this.  In the meantime, after changing the CAMERA variable in config.sh you need to restart the AllSky service.  You can either do this via the command line or simply go to the "Camera settings" page and click on the "Save settings" button without making any changes.
Let me know how that goes

**Comment by EricClaeys** [comment]
@ssagerian Steve, did the fix and/or my suggestion above work?  If so, would you please close the Issue?  Thanks - Eric

**Comment by ssagerian** [comment]
the correct file name now appears in the camera setting page
