### ISSUE TITLE
Saving config.sh in editor window doesnt work.

### ISSUE THREAD

**Issue by ssagerian** [thomasjacquin/allsky-portal#47]
I log onto the PI and run the Admin Panel.
If I go to the script editor window and change a field (in this case CAMERA), save it, then go to another page and return to the script editor page, the changes are gone.
The attached screen shots demonstrate the issue...
Edit_window 1 shows the original script editor page with CAMERA="RPiHQ"
Edit_window 2 shows the value of CAMERA changed to "auto"
Edit_window3 shows the script editor page after saving the changes, going to the live view page then returning back to the  script editor page, the changes are gone, the file "config.sh" does not appear to  have been save
![edit_window1](https://user-images.githubusercontent.com/3128943/136776612-fdc912b7-b0a6-4e77-8df2-c97b09e3f215.png)
![edit_window2](https://user-images.githubusercontent.com/3128943/136776628-25f56e20-47cb-4d03-8ee9-5c1a9cf8758c.png)
d
![edit_window3](https://user-images.githubusercontent.com/3128943/136776660-c3ad0b06-ba5a-4997-b41e-5f325daca89d.png)
.

**Comment by ssagerian** [comment]
The config.sh file was located in the config folder, if I gave you the impression it was somewhere else it was NOT. I am in the process of reinstalling allsky and then the GUI and will test again. Thanks!

**Comment by ckuethe** [comment]
`git log` is your friend. That'll tell you what git revision you're using.

**Comment by EricClaeys** [comment]
@ssagerian Steve, were you able to test as I suggested a few days ago?  If so, how'd it go?

**Comment by ssagerian** [comment]
@EricClaeys Eric, no joy.
![config_sh_lighttpd_log2](https://user-images.githubusercontent.com/3128943/137259075-14780b1e-f24f-41ba-99db-48a5ef02b1cb.png)
.

**Comment by EricClaeys** [comment]
@ssagerian,
Steve, I just submitted some changes that should fix this.  The files that had "/home/pi/allsky" hard-coded are now automatically updated to use $ALLSKY_HOME when the WebUI is installed via `allsky/gui/install.sh`.

When the changes in both "allsky" AND "allsky-portal" are merged you'll need to grab the newest allsky/gui/install.sh.  I suggest doing a complete re-install of the WebUI by executing `cd allsky;  sudo gui/install.sh`.  That'll be easier than grabbing all the files that changed.
The re-install will save and restore any files in /var/www/html/allsky so should be non-destructive.

**Comment by EricClaeys** [comment]
@ssagerian    Steve, any update?

**Comment by EricClaeys** [comment]
Closing - no response.  And the issue was fixed as far as we know.
