### ISSUE TITLE
Images page doesn't display correctly if fontawesome is unavailable

### ISSUE THREAD

**Issue by ckuethe** [thomasjacquin/allsky-portal#9]
Let's say I have a remote allsky that doesn't have internet access, that I just connect to its AP from time to time - if fontawesome is unavailable the image index page doesn't render properly.

I hacked around this by putting `all.js` into the `js/` directory and updating `index.php` to use the local copy, but 657KB of javascrap for 3 icons seems a little excessive.

Could you include just the icons you need in a local file, or add a fallback `[#]` text button so that there are no hard dependencies on remot servers?

**Comment by thomasjacquin** [comment]
Good catch Chris. That's a good idea. I'll update it.

**Comment by thomasjacquin** [comment]
Hi Chris, I have included a local copy of Font Awesome (minified). It's 438 kB. I didn't really have time to look at which icons to package. Also, it's a little easier to leave them all in there in case I need to use new ones, then I don't have to repackage the JS. At least it should work when using it in access point.

**Comment by ckuethe** [comment]
Sounds good to me.
